name: Welcome New Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write  

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on new issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Hi @${{ github.actor }}!

Thanks for opening your first issue 🎉  
We're excited to have you contributing to this project!

Please make sure you've included:
- A clear description of the issue
- Steps to reproduce (if applicable)
- Screenshots or logs (if helpful)

If you're unsure about anything, feel free to ask — we're here to help! 💬  
Stay tuned while someone from the team reviews your issue. 🚀`
            })
